import mongoose from 'mongoose';

export const sample_foods = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Biriyani',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    quantity: 10,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_users = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Diya Chandra',
    email: 'diyachandra22@gmail.com',
    password: '$2a$10$ijTRi9TPcoksDFu3KUSAw.XCYR3mvXd9BhF7m6yAD96B2p87F.cNK',
    address: 'fnffmahjbadjkbfkjefenfk',
    isAdmin: false,
    createdAt: '2024-04-12T14:49:31.162+00:00',
    updatedAt: '2024-04-12T14:49:31.162+00:00',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Gopika Jayaram',
    email: 'gopikajayaram03@gmail.com',
    password: '$2a$10$ijTRi9TPcoksDFu3KUSAw.XCYR3mvXd9BhF7m6yAD96B2p87F.cNK',
    address: 'fnffmahjbadjkbfkjefenfk',
    isAdmin: false,
    createdAt: '2024-04-12T14:49:31.162+00:00',
    updatedAt: '2024-04-12T14:49:31.162+00:00',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Abhijith M',
    email: 'abhijith@gmail.com',
    password: '$2a$10$ijTRi9TPcoksDFu3KUSAw.XCYR3mvXd9BhF7m6yAD96B2p87F.cNK',
    address: 'fnffmahjbadjkbfkjefenfk',
    isAdmin: false,
    createdAt: '2024-04-12T14:49:31.162+00:00',
    updatedAt: '2024-04-12T14:49:31.162+00:00',
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Admin User',
    email: 'admin@gmail.com',
    password: '$2a$10$ijTRi9TPcoksDFu3KUSAw.XCYR3mvXd9BhF7m6yAD96B2p87F.cNK', // bcrypt hashed password for "12345"
    address: 'Admin Street 123, Canteen City',
    isAdmin: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
